Multiarch build

diff --git a/.github/workflows/build-image.yml b/.github/workflows/build-image.yml
--- a/.github/workflows/build-image.yml
+++ b/.github/workflows/build-image.yml
@@ -5,75 +5,230 @@ on:
     types: [published]
   push:
 
-env:
-  VERSION: 3.18
-  GH_USER: chukysoria
-  GH_REPO: docker-baseimage-alpine
-  IMAGE_NAME: baseimage-alpine
-  ARCH: arm32v7
-
 jobs:
-  build:
+  information:
+    name: ℹ️ Gather add-on information
     runs-on: ubuntu-latest
+    outputs:
+      name: ${{ steps.basic.outputs.name }}
+      image: ${{ steps.basic.outputs.image }}
+      description: ${{ steps.basic.outputs.description }}
+      ext_release: ${{ steps.basic.outputs.ext_release }}
+      ext_release_clean: ${{ steps.basic.outputs.ext_release_clean }}
+      architectures: ${{ steps.architectures.outputs.architectures }}   
+      version: ${{ steps.release.outputs.version }}
     steps:
-      - name: Set current date as env variable
-        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
+      - name: ⤵️ Check out code from GitHub
+        uses: actions/checkout@v4
+      
+      - name: ℹ️ Find config file
+        id: find
+        run: |
+          echo "config=build.yml" >> $GITHUB_OUTPUT
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
+      - name: ℹ️ Extract basic image information
+        shell: bash
+        id: basic
+        run: | 
+          name=$(yq --no-colors eval '.name' "${{ steps.find.outputs.config }}")
+          echo "name=${name}" >> "$GITHUB_OUTPUT"
+  
+          description=$(yq --no-colors eval '.description' "${{ steps.find.outputs.config }}")
+          echo "description=${description}" >> "$GITHUB_OUTPUT"
+  
+          image=$(yq --no-colors eval '.image // ""' "${{ steps.find.outputs.config }}")
+          echo "image=${image}" >> "$GITHUB_OUTPUT"
+
+          ext_release=$(yq --no-colors eval '.ext_release' "${{ steps.find.outputs.config }}")
+          echo "ext_release=${ext_release}" >> "$GITHUB_OUTPUT"
+
+          echo "ext_release_clean=$(echo '$ext_release' | sed 's/[~,%@+;:/]//g')" >> "$GITHUB_OUTPUT"
+  
+      - name: ℹ️ Extract add-on architecture information
+        shell: bash
+        id: architectures
+        run: |
+          architectures=$(
+            yq --no-colors --output-format json  eval '.arch' "${{ steps.find.outputs.config }}" \
+              | jq --raw-output --compact-output '. | sort'
+          )
+          echo "architectures=${architectures}" >> "$GITHUB_OUTPUT"
+  
+          for architecture in \
+            aarch64 \
+            amd64 \
+            armhf \
+            armv7 \
+            i386;
+          do
+            available=$(
+              yq --no-colors eval \
+                ".arch[] | select(. == \"${architecture}\") | . or false" \
+                "${{ steps.find.outputs.config }}"
+            )
+            echo "${architecture}=${available}" >> "$GITHUB_OUTPUT"
+          done   
+
+      - name: ℹ️ Gather version
+        id: release
+        run: |
+          version="${sha:0:7}"
+          if [[ "${{ github.event_name }}" = "release" ]]; then
+            version="${{ github.event.release.tag_name }}"
+            version="${version,,}"
+            version="${version#v}"
+          fi
+          echo "version=${version}" >> "$GITHUB_OUTPUT"
+
+  build:
+    name: 👷 Build & Deploy ${{ matrix.architecture }}
+    needs: information
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        architecture: ${{ fromJson(needs.information.outputs.architectures) }}
+    outputs:
+      build_date: ${{ steps.flags.outputs.date }}
+    steps:
+      - name: ℹ️ Compose build flags
+        id: flags
+        run: |
+          echo "date=$(date +"%Y-%m-%dT%H:%M:%SZ")" >> "$GITHUB_OUTPUT"
+          from=$(yq --no-colors eval ".build_from.${{ matrix.architecture }}" "./build.yaml")
+          echo "from=${from}" >> "$GITHUB_OUTPUT"
+
+          if [[ "${{ matrix.architecture }}" = "amd64" || "${{ matrix.architecture }}" = "x86_64" ]]; then
+            echo "platform=linux/amd64" >> "$GITHUB_OUTPUT"
+          elif [[ "${{ matrix.architecture }}" = "i386" ]]; then
+            echo "platform=linux/386" >> "$GITHUB_OUTPUT"
+          elif [[ "${{ matrix.architecture }}" = "armhf" ]]; then
+            echo "platform=linux/arm/v6" >> "$GITHUB_OUTPUT"
+          elif [[ "${{ matrix.architecture }}" = "armv7" ]]; then
+            echo "platform=linux/arm/v7" >> "$GITHUB_OUTPUT"
+          elif [[ "${{ matrix.architecture }}" = "aarch64" ]]; then
+            echo "platform=linux/arm64/v8" >> "$GITHUB_OUTPUT"
+          else
+            echo "::error ::Could not determine platform for architecture ${{ matrix.architecture }}"
+            exit 1
+          fi
+
+      - name: 🏗 Set up build cache
+        id: cache
+        uses: actions/cache@v3.3.2
         with:
-          platforms: arm
+          path: /tmp/.docker-cache
+          key: docker-${{ matrix.architecture }}-${{ github.sha }}
+          restore-keys: |
+            docker-${{ matrix.architecture }}
 
-      - name: Login to Docker Hub
+      - name: 🏗 Set up QEMU
+        uses: docker/setup-qemu-action@v2
+
+      - name: 🏗 Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+        with:
+          platforms: ${{ steps.flags.outputs.platform }}
+
+      - name: 🏗 Login to Github Container Repo
         uses: docker/login-action@v2
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Docker meta
+      - name: 🚀 Calculate image labels and tags
         id: meta
         uses: docker/metadata-action@v4
         with:
           # list of Docker images to use as base name for tags
           images: |
-             ghcr.io/${{ env.GH_USER }}/${{ env.IMAGE_NAME }}            
+             ghcr.io/${{ github.repository_owner }}/${{ needs.information.outputs.image }}            
           # generate Docker tags based on the following events/attributes
+          flavor:
+            prefix=${{ matrix.architecture }}-
           tags: |
-            type=sha,format=long
-            type=raw,value=latest,enable={{is_default_branch}}
-            type=raw,value=${{ github.ref_name }}
-            type=raw,value=${{ env.VERSION }}
-            type=ref,event=branch,prefix=${{ env.VERSION }}-
-            type=ref,event=tag,prefix=${{ env.VERSION }}-
-            type=raw,value=latest,enable={{is_default_branch}},prefix=${{ env.ARCH }}-
-            type=raw,value=${{ github.ref_name }},prefix=${{ env.ARCH }}-
-            type=raw,value=${{ env.VERSION }},prefix=${{ env.ARCH }}-
-            type=ref,event=branch,prefix=${{ env.ARCH }}-${{ env.VERSION }}-
-            type=ref,event=tag,prefix=${{ env.ARCH }}-${{ env.VERSION }}-
+            type=sha,prefix=${{ matrix.architecture }}-${{ needs.information.outputs.ext_release_clean }}-
+            type=sha,suffix=-${{ needs.information.outputs.version }}
           labels: |
-            org.opencontainers.image.created=${{ env.NOW }}
+            org.opencontainers.image.created=${{ steps.flags.outputs.date }}
             org.opencontainers.image.authors=Carlos Sanchez
-            org.opencontainers.image.url=https://github.com/${{ env.GH_USER }}/${{ env.GH_REPO }}/packages
+            org.opencontainers.image.url=https://github.com/${{ github.repository_owner }}/${{ github.repository }}/packages
             org.opencontainers.image.documentation=https://docs.linuxserver.io/images/docker-baseimage-alpine
-            org.opencontainers.image.source=https://github.com/${{ env.GH_USER }}/${{ env.GH_REPO }}
-            org.opencontainers.image.version=${{ github.ref_name }}-ls
+            org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/${{ github.repository }}
+            org.opencontainers.image.version=${{ needs.information.outputs.version }}
             org.opencontainers.image.revision=${{ github.sha }}
             org.opencontainers.image.vendor=Carlos Sanchez
             org.opencontainers.image.licenses=GPL-3.0-only
             org.opencontainers.image.ref.name=${{ github.sha }}
-            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
-            org.opencontainers.image.description=baseimage-alpine image by Carlos Sanchez        
+            org.opencontainers.image.title=${{ needs.information.outputs.name }}
+            org.opencontainers.image.description=${{ needs.information.outputs.description }} 
 
-      - name: Build and push
+      - name: 🚀 Build and push
         uses: docker/build-push-action@v4
         with:
-          platforms: linux/arm/v7
-          push: ${{ github.event_name == 'release' }}
+          load: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
-          pull: true
+          cache-from: |
+            type=local,src=/tmp/.docker-cache
+            ghcr.io/${{ github.repository_owner }}/${{ needs.information.outputs.image }}
+          cache-to: type=local,mode=max,dest=/tmp/.docker-cache-new          
+          platforms: ${{ steps.flags.outputs.platform }}
+          push: ${{ github.event_name == 'release' }}
           build-args: |
-            OS=${{ env.ARCH }}
-            VERSION=${{ github.ref_name }}
-            BUILD_DATE=${{ env.NOW }}
+            BUILD_ARCH=${{ matrix.architecture }}
+            BUILD_DATE=${{ steps.flags.outputs.date }}
+            BUILD_EXT_RELEASE=${{ needs.information.outputs.ext_release }}
+            BUILD_FROM=${{ steps.flags.outputs.from }}
+            BUILD_VERSION=${{ needs.information.outputs.version }}
+
+      # This ugly bit is necessary, or our cache will grow forever...
+      # Well until we hit GitHub's limit of 5GB :)
+      # https://github.com/docker/build-push-action/issues/252
+      # https://github.com/moby/buildkit/issues/1896
+      - name: 🚚 Swap build cache
+        run: |
+          rm -rf /tmp/.docker-cache
+          mv /tmp/.docker-cache-new /tmp/.docker-cache
+
+  publish:
+    name: 👷 Publish manifest
+    runs-on: ubuntu-latest
+    needs:
+      - information
+      - build
+    if: ${{ github.event_name == 'release' }}
+    steps:
+      - name: 🏗 Login to Github Container Repo
+        uses: docker/login-action@v2
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: 🚀 Calculate manifest image labels and tags
+        id: meta
+        uses: docker/metadata-action@v4
+        with:
+          # list of Docker images to use as base name for tags
+          images: |
+             ghcr.io/${{ github.repository_owner }}/${{ needs.information.outputs.image }}            
+          # generate Docker tags based on the following events/attributes
+          tags: |
+            type=sha,prefix=${{ needs.information.outputs.ext_release_clean }}-
+            type=sha,prefix=,suffix=-${{ needs.information.outputs.version }}
+      
+      - name: 🚀 Calculate source images
+        id: source
+        run: |
+          for arch in ${{ needs.information.outputs.architectures }}; do
+              echo "$(ghcr.io/${{ github.repository_owner }}/${{ needs.information.outputs.image }}:$arch-latest)" >> images.txt
+          done
+          echo "images=$(cat images.txt)" >> GITHUB_OUTPUT
+
+      - name: 🚀 Create and push manifest images
+        uses: Noelware/docker-manifest-action@0.4.0
+        with:
+            inputs: ${{ steps.meta.outputs.tags }}
+            images: ${{ steps.source.outputs.images }}
+            push: true
